### ISSUE TITLE
having junit format for jenkins 

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#331]
## Description:

once we move to Jenkins for the testacc and use pipelines, we want also to produce junit so we can benifits from jenkins functionalities. ( like nice tests-reports  and we can also fetch the results by other 3rd party apps)

## Tasks:

- [ ] research about good golang plugin. Found already this https://github.com/jstemmer/go-junit-report
- [ ] add needed pkg to upstream
- [ ] update current tests
