### ISSUE TITLE
run testsuite on Jenkins CI:

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#338]
## Description:
Move travis-ci to jenkins ci.

## Design proposal:
I would vote to use jenkins-pipelines and having the `terraform-provider-libvirt` in a container.
Having the plugin in container ( this managed by pipelines with [docker](https://jenkins.io/doc/book/pipeline/docker/)) we can have freedom for testing multi-distros

### infra:
- [ ] resolve infra hw question (slave, etc)
- [ ] create salt-states for setting-up jenkins-slave

## Branch tests (master)
- [ ] create needed pipelines for testacc
- [ ] cover ubuntu/centos/fedora.

### PRs tests 
- [ ] create extra pipeline if needed for PRs
- [ ] create a CI-user bot used via API for gitarro
- [ ] for tests on PRs use https://github.com/openSUSE/gitarro  

## Code coverage 

- [ ] research tool how we could evaluate the code-coverage golang in a jenkins env.

# Jenkins extra
- [ ] add junit https://github.com/dmacvicar/terraform-provider-libvirt/issues/331
- [ ] use jenkins-job-buider or similar for automating job-creation

# Performance:
- [ ] evaluate if we want also to have prometheus/grafana libvirt-exporter in our slave where we execute the tests and also node-exporter for monitoring the slave and performance of our tests

# Releasing:
- [ ] evaluate the use of https://github.com/cornelius/yes_ship_it in our golang context  ( i think it can be usefull)

# Community terraform-files:

- [ ] evaluate if we could do a sort of survey where the community give us terraform.tf libvirt files and we can ensure that this are working or branch tests (release checks) https://github.com/dmacvicar/terraform-provider-libvirt/issues/339

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/issues/334

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/issues/331

**Comment by MalloZup** [comment]
i don"t think we might endup doing this ever .. :smile:

**Comment by driv** [comment]
Where will this run?

**Comment by driv** [comment]
I'm trying to run the tests locally, but I'm getting the same error as in https://travis-ci.org/dmacvicar/terraform-provider-libvirt/builds/432832819?utm_source=github_status&utm_medium=notification.
What is not supported on Travis that tests need to be disabled?

**Comment by MalloZup** [comment]
@driv for run tests locally use make testacc this works
